---
title: "02 ARMA-GARCH Forecasts - Sensitivity anaysis: rebalancing period"
---

Loading required libraries

```{r}
libraries <- c("aTSA", "forecast", "nloptr", "rugarch", "xts", "zoo")

for(i in libraries){
  installed <- require(i, character.only = TRUE)
  
  if(installed == FALSE){
    install.packages(i)
  }
}

rm(i, installed, libraries)
```

Loading constituents list for the day before firs day of every period

```{r}
# for 1- and 3-month rebalancing window

df <- read.csv("c_list.csv", sep = ",", header = TRUE, row.names = 1)
df <- as.xts(df)

# for 2-week rebalancing period

df2 <- read.csv("c_list_f_05.csv", sep = ",", header = TRUE, row.names = 1)
df2 <- as.xts(df2)
```

Loading price data

```{r}
load("price_data.Rda")
```

Initializing functions required to handle time data

```{r}
get_month_length <- function(date){
  year <- as.numeric(format(date, '%Y'))
  if((year %% 4 == 0 & year %% 100 != 0) | year %% 400 == 0){
    month_days_number = c(31,29,31,30,31,30,31,31,30,31,30,31)
  }else{
    month_days_number = c(31,28,31,30,31,30,31,31,30,31,30,31)
  }
  
  month <- as.numeric(format(date, '%m'))
  return(month_days_number[month])
}

months_forward <- function(date, n){
  if(n == 0){
    return(date)
  }
  
  new_date <- date
  for(i in 1:n){
    new_date = new_date + get_month_length(new_date)
  }
  
  return(new_date)
}
```

```{r}
# n - days ahead
# p, q - ARMA order
# garch_distr - garch error distribution
# est_seed - seed

get_garch_forecast <- function(returns, n, p, q, garch_distr, est_seed){
  
  set.seed(est_seed)

  skip_garch <- FALSE
  log <- " - solver converged, ARCH effects present - model: ARIMA-GARCH"
  
  test_model <- arima(returns, order = c(p, 0, q), include.mean = TRUE, method = "ML")
  
  arch_test <- arch.test(test_model, output = FALSE)
  
  if(min(arch_test[, 5]) > 0.05){
    skip_garch = TRUE
  }

  specification <- ugarchspec(
    variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
    mean.model = list(armaOrder = c(p, q), include.mean = TRUE), distribution.model = garch_distr)
    
  tryCatch(
    expr = {model <- ugarchfit(spec = specification, data = returns)}, #, solver = "hybrid"
    warning = function(e) {skip_garch <<- TRUE},
    error = function(e) {skip_garch <<- TRUE}
    )
    
  if(skip_garch == TRUE){
    log <- " - either solver failed to converge or no ARCH effects - model: ARIMA"
    model <- arima(returns, order = c(p, 0, q), include.mean = TRUE, method = "ML")
    prediction <- predict(model, n.ahead = n)
    return(list(prediction$pred, log))
  } else {
    prediction <- ugarchboot(model, n.ahead = n, method = c("Partial", "Full")[1], n.bootpred=10000, n.bootfit=10000)
    return(list(prediction@forc@forecast$seriesFor, log))
  }
}
```

```{r}
#seed: 2611

#####################
# f = 0.5 (2 weeks) #
#####################

# ------ PARAMETER SETTING SECTION ------

#portfolio rebalancing window length (months)
f <- 1

#number of assets
n <- 30

#estimation window (months)
t <- 12

#beginning date of the first estimation window
est_date <- as.Date('2006-01-01', '%Y-%m-%d')

#beginning date of the first rebalancing period
start_date <- as.Date('2007-01-01', '%Y-%m-%d')

#path for the results folder
path_folder <- "arima-garch_forecasts_f_05"
path <- paste0(path_folder, "/")

#description in the log file
log_descr <- "ARIMA-GARCH Forecasts: SA - rebalancing period: 0.5 month, seed: 2611"

#ARIMA(p, 1, q) order
p <- 2
q <- 1

#GARCH(1, 1) error distribution
garch_error_distr <- "norm"

# ------ END OF PARAMETER SETTING SECTION ------

log_file <- data.frame(matrix(nrow = 1, ncol = 1))
log_file[1, 1] <- log_descr

ptm <- proc.time()

for(i in 320:418){ #418
  
  forecasts_df <- data.frame()
  forecasts_df_colnames <- NULL
  
  for(j in 1:30){
    
    if(df2[start_date + 14 * i, j] != "GM"){
      print(paste("Period no (i + 1): ", i + 1, "/418 - Stock no (j): ", j, "/30 - Progress: ", round((j + i * 30) / ( 418 * 30 ) * 100, digits = 2), "%" , sep = ""))
      
      subset <- price_data[paste0(est_date + 14 * i, "/", months_forward(est_date + 14 * i, t)-1), df2[start_date + 14 * i, j]]
      
      #print(df[months_forward(start_date, i+t), j])
      
      subset_logreturns <- log(subset / lag(subset, 1, na.pad=TRUE))
      subset_logreturns <- na.omit(subset_logreturns)
      
      #DOW quick fix
      if(i == 320 & j == 30){
        x <- rep(0, 30)
      } else {
        x <- NULL
        x <- get_garch_forecast(subset_logreturns, 30, p, q, garch_error_distr, 2611)
      }
      
      if(j == 1){
        forecasts_df <- x[[1]]
      } else if(df2[start_date + 14 * i, j] == "DOW"){
        tmp <- as.numeric(x[[1]])
        forecasts_df <- cbind(forecasts_df, tmp)
      } else {
      forecasts_df <- cbind(forecasts_df, x[[1]])
      }
      
      log_line <- paste0("[", Sys.time(), "] period: (", i + 1, "/418): ", months_forward(start_date, i), "/", months_forward(start_date, i+t)-1,
                         " - stock: (", j, "/30): ", df2[start_date + 14 * i, j], 
                         x[[2]])
      
      log_file <- rbind(log_file, log_line)
      
      forecasts_df_colnames <- c(forecasts_df_colnames, colnames(subset))
      
      #readline()
    }
  }
  
  colnames(forecasts_df) <- forecasts_df_colnames
  
  write.csv(forecasts_df, file = paste0(path, start_date + 14 * i, ".csv", sep = ""))
  
  #print(df[months_forward(start_date, i+t)])
  
  
  #print(paste(
  #  "Estimation window: ", months_forward(start_date, i), "-", months_forward(start_date, i+t)-1,
  #  "Rebalancing window: ", months_forward(start_date, i+t), "-", months_forward(start_date, i+t+f)-1))
}

write.table(log_file, file = paste0(path, "log2.txt", sep = ""), sep = "", col.names = FALSE, row.names = FALSE, quote = FALSE)

proc.time() - ptm
```


```{r}
#seed: 2611

#########
# f = 3 #
#########

# ------ PARAMETER SETTING SECTION ------

#portfolio rebalancing window length (months)
f <- 3

#number of assets
n <- 30

#estimation window (months)
t <- 12

#beginning date of the first estimation window (then first rebalancing period is start_date + t months)
start_date <- as.Date('2006-01-01', '%Y-%m-%d')

#path for the results folder
path_folder <- "arima-garch_forecasts_f_3"
path <- paste0(path_folder, "/")

#description in the log file
log_descr <- "ARIMA-GARCH Forecasts: SA - rebalancing period: 3 months, seed: 2611"

#ARIMA(p, 1, q) order
p <- 2
q <- 1

#GARCH(1, 1) error distribution
garch_error_distr <- "norm"

# ------ END OF PARAMETER SETTING SECTION ------

log_file <- data.frame(matrix(nrow = 1, ncol = 1))
log_file[1, 1] <- log_descr

ptm <- proc.time()

for(i in 0:63){
  
  forecasts_df <- data.frame()
  forecasts_df_colnames <- NULL
  
  for(j in 1:30){
    
    if(df[months_forward(start_date, f * i + t), j] != "GM"){
      print(paste("Period no (i + 1): ", i + 1, "/64 - Stock no (j): ", j, "/30 - Progress: ", round((j + i * 30) / ( 64 * 30 ) * 100, digits = 2), "%" , sep = ""))
      
      subset <- price_data[paste0(months_forward(start_date, i * f), "/", months_forward(start_date, f * i+t)-1), df[months_forward(start_date, i * f + t), j]]
      
      #print(df[months_forward(start_date, i+t), j])
      
      subset_logreturns <- log(subset / lag(subset, 1, na.pad=TRUE))
      subset_logreturns <- na.omit(subset_logreturns)
      
      x <- NULL
      x <- get_garch_forecast(subset_logreturns, 63, p, q, garch_error_distr, 2611)
      
      if(j == 1){
        forecasts_df <- x[[1]]
      } else {
      forecasts_df <- cbind(forecasts_df, x[[1]])
      }
      
      log_line <- paste0("[", Sys.time(), "] period: (", i + 1, "/64): ", months_forward(start_date, i * f), "/", months_forward(start_date, i * f + t)-1,
                         " - stock: (", j, "/30): ", df[months_forward(start_date, f * i+t), j], 
                         x[[2]])
      
      log_file <- rbind(log_file, log_line)
      
      forecasts_df_colnames <- c(forecasts_df_colnames, colnames(subset))
      
      #readline()
    }
  }
  
  colnames(forecasts_df) <- forecasts_df_colnames
  
  write.csv(forecasts_df, file = paste0(path, months_forward(start_date, f * i + t), ".csv", sep = ""))
  
  #print(df[months_forward(start_date, i+t)])
  
  
  #print(paste(
  #  "Estimation window: ", months_forward(start_date, i), "-", months_forward(start_date, i+t)-1,
  #  "Rebalancing window: ", months_forward(start_date, i+t), "-", months_forward(start_date, i+t+f)-1))
}

write.table(log_file, file = paste0(path, "log.txt", sep = ""), sep = "", col.names = FALSE, row.names = FALSE, quote = FALSE)

proc.time() - ptm
```
